{
 "title": "Bacula",
 "description": "bacula dash",
 "tags": [ "bacula" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Failed jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "Bacula" },
     "host": { "filter": "riobac001" },
     "item": { "filter": "Bacula Director is running" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT JobId, Name, JobStatus, JobBytes, StartTime, EndTime\r\nFROM Job\r\nWHERE JobStatus != 'T'\r\nORDER BY EndTime DESC;",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Faild Job alerts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(name) AS failed_jobs\r\nFROM job\r\nWHERE jobStatus = 'f'\r\nAND endTime >= NOW() - INTERVAL '1 days';\r\n"
    }
   ]
  },
  {
   "title": "Terminates status of Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT JobStatus AS JobStatus, COUNT(*) AS count FROM job GROUP BY JobStatus ORDER BY count DESC\n"
    }
   ]
  },
  {
   "title": "Size of Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Name AS Name, SUM(Job.JobBytes) AS Size FROM job GROUP BY Name ORDER BY Size DESC LIMIT 50000;\r\n"
    }
   ]
  },
  {
   "title": "/",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "application": { "filter": "Filesystem" },
     "host": { "filter": "riobac001" },
     "item": { "filter": "Total disk space on /" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT name,numvols From pool;\n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystem" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "riobac001" },
     "item": { "filter": "Used disk space on /" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(name) FROM pool;\n"
    }
   ]
  },
  {
   "title": "Bacula Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(Name)\nFROM\n  client;\n"
    }
   ]
  },
  {
   "title": "Volume Size of CGG Backup",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(VolBytes) FROM media ;\n"
    }
   ]
  },
  {
   "title": "Number of Tapes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(VolumeName)\nFROM\n  media\n;"
    }
   ]
  },
  {
   "title": "Last 500 Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select JobID,Name,JobStatus,StartTime,EndTime,Level,JobFiles,JobBytes FROM job  ORDER BY StartTime DESC LIMIT 500;\r\n"
    }
   ]
  },
  {
   "title": "Backup Sizes Total from day 0",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "application": { "filter": "Bacula" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Backup.*Bytes/" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT SUM(jobbytes) / 1048576 AS Megabytes FROM job;\r\n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Logs  per jobid",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT logid,logtext FROM log ;"
    }
   ]
  }
 ]
}